version: '3.3'

services:
  postgres: 
    container_name: nest-clean-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: nest-clean
      PGDATA: /data/postgres 
    volumes:
      - ./data/pg:/data/postgres